### ISSUE TITLE
Separation of alternating time signatures

### ISSUE THREAD

**Issue by ahankinson** [rism-digital/pae-code-spec#103]
Currently alternating time signatures are separated by a space. However, this may be a challenge when processing changes to time signatures, since the space character is used to separate changes from the following music notation. 

Another character should be used instead; I am proposing the use of the pipe character (`|`). This character is commonly used to indicate "OR" in regular expressions (e.g., a|b  == "a OR b"). 

I understand that the pipe character is not that easy to use on some keyboards. However, alternating time signatures are also not very common. As best as I can tell, there are roughly 40 incipits in RISM Online that feature an alternating time signature. (0.002% of all incipits)

**Comment by BaMikusi** [comment]
Just to register this also under this issue: for RISM catalogers in particular, finding the `|` should be unproblematic since they are expected regularly to use it for their title descriptions in the 245 field.

**Comment by BaMikusi** [comment]
Sorry, I have one more question on this: How are we to encode the following?
![grafik](https://github.com/rism-digital/pae-code-spec/assets/70342380/8dc85cf0-2a5f-4fa3-a218-5aa6d2657b44)
Presumably `2/8 | 2/8 | 3/8` ?
(This being a really complex case, it may be okay if it cannot be rendered absolutely faithfully in PAE, if we have no better guess.)
However, the specifications now say "CWMN time signatures that indicate alternating measures MAY be indicated by transcribing both," and that seems not quite to apply here, since we are not speaking of "alternating _measures_" but rather about _time signatures_ that in fact alternate inside a single measure, and the "both" is also not quite appropriate, since we could have more than two time signatures involved.
Finally, this MAY should at least be a SHOULD in my opinion, since encoding only some part of a characteristically complex time signature is anything but helpful for identification purposes.
So, overall, perhaps better say something like this:
"In CWMN alternating time signatures SHOULD be indicated by transcribing each one of them."
(And, of course, it then goes on with "These MUST be separated by a vertical bar | character.")

**Comment by ahankinson** [comment]
The actual time signature is `7/8`. There is no need to give the beaming groups in the time signature. That is someone trying to be too clever by half. If I were to give them the benefit of the doubt, I would say that they're trying to be helpful for a performer, but incipits are not a performance medium... 

`2/8 | 3/8 | 2/8` would not work, as you said, because it doesn't alternate by measure. And I think the intention is that we only allow two alternations, so `2/8 | 3/8 | 4/4` would not be allowed. 

I put it as MAY because it's possible that alternating time signature changes are given at each bar, and so the MAY allows the option -- either you can do it at the beginning, or at every bar, as needs dictate. Changing that to SHOULD would imply that alternating changes, even when rendered at every measure, should be collapsed into a single time signature. 

More specifically to the meaning behind the normative language, the SHOULDs, in theory, will raise a warning in software tools that this is allowed, but not recommended.

```
SHOULD   This word, or the adjective "RECOMMENDED", mean that there 
may exist valid reasons in particular circumstances to ignore a particular 
item, but the full implications must be understood andcarefully weighed 
before choosing a different course.
```

https://datatracker.ietf.org/doc/html/rfc2119#section-3

**Comment by BaMikusi** [comment]
The "too clever by half" guy happens to be Bartók:
https://musescore.com/user/37481236/scores/7416989

**Comment by ahankinson** [comment]
I rest my case. 😀

**Comment by BaMikusi** [comment]
And here, too, there are "meters of mixed denominators" that appear in a single measure:
https://www.scoringnotes.com/tutorials/composite-time-signatures-in-sibelius/

**Comment by ahankinson** [comment]
Isn't that "just" 5/4? 

The other option we have is that time signatures have absolutely no bearing on the meter, and are simply recorded as a visual value. This is what we are leaning towards in tuplets, but it may also be changed to apply here. 

Since we anyway manually insert barlines and note durations, then the time signature actually has no effect.

**Comment by BaMikusi** [comment]
I guess if the composer had felt that 5/4 gave the proper hint for the performer, he would have written that, so I think we shouldn't just count the noteheads and put a normalized meter at the beginning, instead of what stands in the source. Also because an irregular meter is very conspicuous in itself, and so it is a useful point of identification -- as well as a potential point of interest for researchers.

**Comment by BaMikusi** [comment]
(And I while I am aware this is all crazy stuff, and was certainly not something Barry Brook had in mind when conceiving the original PAE, there are in fact more and more estates by contemporary composers cataloged in Muscat, and in those manuscripts any of this mess could indeed appear.)
