### ISSUE TITLE
Change + in clef to * for mensural notation

### ISSUE THREAD

**Issue by ahankinson** [rism-digital/pae-code-spec#119]
The `+` character gives some problems when needing to be URL encoded (see: #1 ). Ties no longer use `+`, but clefs for mensural do. We should change this to use `*` instead of `+`.

**Comment by BaMikusi** [comment]
Is the `*` suggested out of the blue here, or does it have some obvious advantages for this specific function?

**Comment by lpugin** [comment]
The `+` is problematic in URLs. See https://github.com/rism-digital/pae-code-spec/issues/1

**Comment by BaMikusi** [comment]
Sure, but why precisely the `*` should take its place? (Not doubting, just wondering if there is a specific advantage to that.)

**Comment by ahankinson** [comment]
There are a limited number of characters left. No specific advantage. You can see I changed the title because I was initially suggesting a dot ( . ) but we decided that it could get visually lost and opted for something a bit more visually prominent.

**Comment by lpugin** [comment]
With `-`, `*` and `:`, all clef middle symbols are (incidentally) mathematical operators, which might be a good way do remember them (and `+` was too, obviously)

**Comment by BaMikusi** [comment]
Well, `*` is an arithmetic operator for programmers, but most laymen will tend to use `x` to indicate multiplication.

Whereby, if you take the programmer's stance, the `:` will no longer be an arithmetic operator (but I am mentioning this merely for fun, not as a decisive counterargument).

But I indeed asked about the reasoning behind the asterisk, because quite a few users might not have an idea where the `*` sits on the keyboard (not that they would have to reproduce it themselves in an average PAE user scenario).

**Comment by ahankinson** [comment]
Most ASCII punctuation is also a mathematical operator. That's why it's in ASCII. (They primarily needed to do math on mainframes, which is where ASCII was first defined.) If the humanists had designed it we would have had æ, ¶, §, ¬, … and ‡ instead. 😄

**Comment by ahankinson** [comment]
Keyboard layout was considered for the vertical bar (`|`). I wasn't aware that the asterisk is also difficult on some keyboards?

(The use of `x` for multiplication gets confusing if you have variables... "y x x" or "y * x". )

**Comment by lpugin** [comment]
(The arithmetical argument was really a side one.)

**Comment by BaMikusi** [comment]
@lpugin Sure, I understand -- sorry about taking you up on that.

@ahankinson Though I must still add that laymen tend not to add up variables, but actual numbers, and hence get away with the `x`.

**Comment by BaMikusi** [comment]
But more seriously: the `*` is not that difficult to find, I merely meant to say that it is not a character one tends often to use, outside of special contexts.

Whereby, in a RISM context, the `|` is less of an issue, since we actually expect our catalogers to make regular use of that in the title descriptions for the 245 field.
