### ISSUE TITLE
Rename "Ornaments" section to cover fermata

### ISSUE THREAD

**Issue by ahankinson** [rism-digital/pae-code-spec#140]
From @BaMikusi's feedback:

> “Ornaments alter the performance of a note, a rest, or groups thereof.”
> I still find it very odd to assume that a rest could have an ornament – this presumably hints at the fermata, but the fermata is really not an ornament (as the latter word is used as a rule, and we should not divert from the general usage this far). I understand that, in the context of PAE, in 4.4.2 the fermata is listed under 4.4 Ornaments, but that should also be somehow amended – perhaps call 4.4 in general “Ornamental attributes” or the like? That way I could imagine the fermata standing there, while under “Ornaments” I cannot.

Perhaps we can rename this section "Ornaments and Articulations"? That would cover the fermata, as far as I know.

**Comment by BaMikusi** [comment]
Thanks for giving this some thought, but I am not sure if the above pairing works, for _in abstracto_ one can say that rests and fermata are ways to articulate the flow of music, but if I use "articulations" next to "ornaments," a rather different sphere pf associations opens up, largely things that PAE otherwise ignores, like staccatos, accent marks or even slurs.

**Comment by lpugin** [comment]
What about simply "Ornaments and fermatas" ? I agree with Balázs that articulations is not really appropriate for fermatas, and since we do not have the typical articulation signs, it does not make really sense.

**Comment by ahankinson** [comment]
For what it's worth, both [MuseScore](https://musescore.org/en/handbook/3/articulations-and-ornaments) and [Finale](http://usermanuals.finalemusic.com/Finale2014Win/Content/Finale/Fermatas.htm) refer to a fermata as an articulation.

What about "Expression Marks"? Or "Expressions"? "Ornaments and Fermatas" are weird because it's a class of markings, paired with a single mark, and we only have one fermata type, so the plural does not really fit here.

**Comment by lpugin** [comment]
Musescore changed it in version 4 and it is now in [Expressive marking](https://musescore.org/en/handbook/4/notation-expressive-markings).  I am quite OK with "Expression Marks".

**Comment by BaMikusi** [comment]
Thanks for these hints at Finale and MuseScore (in Version 4 of which the fermata poetically ends up under "Breaths and Pauses") -- all of that is good to know, if only to see that others have been struggling with the same problems when trying to organize each bit of the notation in neat categories. BTW, if we wanted to go the MuseScore way, not even "Ornaments" (in the plural) would be quite appropriate, since out of the variants listed there under this label PAE only deals with the trill, while for the grace notes MuseScore has a separate category. So, we can kind of take it for granted that, whatever we do, there will be edges that stand out.

With that in mind, I would actually be completely fine with with "Ornaments and fermata" (in the singular), but if you feel there has to be a higher-level category here, rather than kind of a listing of what is to come, I can live with "expression" as well. Only one more tiny detail: to my ear "Expression marks" somehow suggests the trill and the fermata, i.e. cases where a single character does the trick, whereby a complex group of gracenotes somehow seems better described by "marking."

**Comment by lpugin** [comment]
Behind Bars has fermatas in the "Pauses" section of the "Metre" chapter. Just for the records, since that would not really be appropriate for us.

Maybe we can call the section "Expression codes" ? That would maybe be better for more complex structures, such as grace notes.

**Comment by BaMikusi** [comment]
Good enough for me.

**Comment by ahankinson** [comment]
How about "Expressions"? All the parts of the spec relate to "codes" so that is redundant.

**Comment by BaMikusi** [comment]
I'm afraid that's too vague; looking at it most readers would likely have no idea what to expect below. Then better go back to "marks" or "marking."

**Comment by ahankinson** [comment]
If "Expressions" is too vague, then "Marks" seems even more vague and generic.

**Comment by BaMikusi** [comment]
Sorry, it was me putting it vaguely this time -- I actually meant returing to  "Expression marks" or "Expressive marking."

**Comment by BaMikusi** [comment]
Out if which the first one is perhaps easier to graps, afer all.

**Comment by ahankinson** [comment]
OK, let's go with "Expression Marks"...
