### ISSUE TITLE
Encoding chord

### ISSUE THREAD

**Issue by lpugin** [rism-digital/pae-code-spec#2]
The current specifications of PAE support the encoding of chords with the `^` character. 

From the current specifications

> Enter chords from the highest to the lowest note, each one separated by `^`.
> 
> Example: `''2D^'A^xF`

There are several issues with this approach:
* Parsing chords is problematic because the start of a chord is given retrospectively when the second note is encountered
* there are no clear specifications for tied chords. Since chords have to be encoded from the highest note to the lowest, the tie between two chords will always be (except for unison chords) between two notes with a different pitch, which is problematic.
* chords can have conflicting note durations
* how to apply a trill or a fermata to chord is not clearly defined

The proposal would be to change the chords to a container markup. To preserve some graphical similarity with the current `^`, a proposal would be to use `<` and `>`. These characters are not used elsewhere in PAE.

Example `2<''D'AxF>`

Some rules would be:
* Duration encoding should be given before the `<` chord start delimiter
* Chord delimiters should contain only pitch related information (octave, accidental and pitch name) 
* Ties should follow `>` chord end delimiters

It would need to be decided if fermata and trills should be outside or inside chord delimiters

**Comment by lpugin** [comment]
It seems to be between 2) or 3). I still believe we can have a good V2 to which we can upgrade all the RISM data without dropping (significant amount of) data.

**Comment by lpugin** [comment]
The I would stay way from both `<` AND `>`. Using only `>` actually does not make it better than using both. The theory is that you do not have to escape it because `<subfield>^ABC></subfield>` is valid. However, libraries might to `<subfield>^ABC&gt;</subfield>`, so in the end we have not avoided the problem. This is what happens with LibXML in ruby, at least.

**Comment by ahankinson** [comment]
I think it’s ok if a library encodes any characters , but having an unencoded `<` is going to kill lots of things.

**Comment by BaMikusi** [comment]
One point we haven't addressed above is the 'direction' for the encoding.

The present specifications ask the cataloger to enter the notes "from the highest to the lowest" -- a point that always gave me a pause, for I would instincitively do this the other way round, from bottom to top. Not simply on acoustical grounds, but rather because that should be the natural way to play chords on string instruments (and in fact even on the keyboard, if an arpeggio is expected, that will normally go from bottom to top -- unless there is a very explicite remark to do the contrary).

So, I would suggest to change this preference -- either by removing such a clause entirely (for inside a container it might actually be all the same, in which order the notes are given), or, if we still mean to have a clear stance on this in the specs, prescribe the bottom-to-top direction for all.

(_Unless_ having the top note at the beginning might be any help for the parsing, when you try to focus the incipit search on the actual melody, as a rule given in the top voice.)

**Comment by lpugin** [comment]
When I code chords, I do start from the top note. But I am probably biased since I probably just have in mind that a parser that ignores chords would only consider the first one, and that having the top one coded first would still fulfils the requirement that incipits should encode the top notes.

Your point makes much more sense, and I don't have a strong opinion on it. I would only suggest to have a decided order as a recommendation only since fixing existing incipits might be quite tricky to do.

**Comment by BaMikusi** [comment]
Sorry, I am just going through all the commented tickets one by one, and haven't checked what you proposed for this in the V2 draft. But then we've been in agreement anyway.

**Comment by ahankinson** [comment]
No worries! Good to have this feedback however it comes
