### ISSUE TITLE
Specify how to encode tied chords

### ISSUE THREAD

**Issue by carlolic** [rism-digital/pae-code-spec#60]
In the spec (V1) there is no explanation how to encode tied chords (the problematic is already mentioned in V2). Some users overcame this by applying own rules:
- adding a + after each note in the chord, e.g. C+^E+^G+C^E^G
- adding a single + between the chords, e.g. C^E^G+C^E^G
Whereas the second approach would only work if the two chords are identical, the first approach would give more flexibility if not all the notes in the chord are tied. However it would be to specify whether + or ^ should directly follow the note.

**Comment by ahankinson** [comment]
This should be considered with #2 and #1 as well. 

```
<CEG>_<CEG>
```

or, to tie only certain notes in a chord,

```
<C_E_G><CEG>
```

**Comment by lpugin** [comment]
> or, to tie only certain notes in a chord,
> ```<C_E_G><CEG>```

I would not allow this. Only ties between the whole chords.

**Comment by ahankinson** [comment]
Based on #112 and #110, the same mechanism for tied notes can be applied to tied chords. 

`^CEG>_`

Would be two C Major chords tied together. Much like the notes, the `_` would stand for the previously-stated chord, so it could also be part of other groups, or have its duration altered.

`^2xCxExG>/4_`

Would be a half-note C# Major chord tied over a barline to a quarter-note C# major chord. Note that this *doesn't* allow for repeating the accidentals in the following chord, so that's one limitation. But in a tied note the pitches are the same, so repeating is mostly a "cautionary" indicator.

This, however, would be possible:

`^2CEG>8(6{_^DxFA>^EGB>})`

![image](https://github.com/rism-digital/pae-code-spec/assets/163183/e1315a32-126b-4a0e-b9cc-0b7b1e61d389)

(Except that the first and second chords are tied)
